name: run_bot

on:
  schedule:
    - cron: '*/2 8-23 * * *'

  workflow_dispatch:

jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - name: Call the bot endpoint to load transactions
        run: |
          curl --request GET \
          --url 'https://finances-bot.vercel.app/api/get-tasks'
